"""Initial PlanGuard schema

Revision ID: e55592f151e2
Revises: 
Create Date: 2026-07-29 19:37:05.523402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55592f151e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('available_study_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('course_weight', sa.Float(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_id', name='uq_assignment_user_provider_id')
    )
    op.create_table('availability_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starts_at_time', sa.Time(), nullable=False),
    sa.Column('ends_at_time', sa.Time(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_override', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_override_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_override_user_id'), ['user_id'], unique=False)

    op.create_table('integration_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('provider_account_email', sa.String(length=255), nullable=True),
    sa.Column('granted_scopes', sa.JSON(), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cached_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_integration_user_provider')
    )
    with op.batch_alter_table('integration_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_state_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('starts_at_time', sa.Time(), nullable=False),
    sa.Column('ends_at_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_availability_user_id'), ['user_id'], unique=False)

    op.create_table('focus_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('assignment_title', sa.String(length=180), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accumulated_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_resumed_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_session_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_session_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_session_user_id'), ['user_id'], unique=False)

    op.create_table('notion_import_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('property_schema', sa.JSON(), nullable=False),
    sa.Column('property_mapping', sa.JSON(), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_summary', sa.JSON(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notion_import_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notion_import_source_integration_id'), ['integration_id'], unique=True)

    op.create_table('o_auth_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('o_auth_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_o_auth_credential_integration_id'), ['integration_id'], unique=True)

    op.create_table('scheduled_focus_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_focus_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_focus_block_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_focus_block_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_focus_block_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_focus_block_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_focus_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_focus_block_user_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_focus_block_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_focus_block_starts_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_focus_block_assignment_id'))

    op.drop_table('scheduled_focus_block')
    with op.batch_alter_table('o_auth_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_o_auth_credential_integration_id'))

    op.drop_table('o_auth_credential')
    with op.batch_alter_table('notion_import_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notion_import_source_integration_id'))

    op.drop_table('notion_import_source')
    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_focus_session_status'))
        batch_op.drop_index(batch_op.f('ix_focus_session_assignment_id'))

    op.drop_table('focus_session')
    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_availability_user_id'))

    op.drop_table('weekly_availability')
    with op.batch_alter_table('integration_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_state_user_id'))

    op.drop_table('integration_state')
    with op.batch_alter_table('availability_override', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_override_user_id'))
        batch_op.drop_index(batch_op.f('ix_availability_override_date'))

    op.drop_table('availability_override')
    op.drop_table('assignment')
    op.drop_table('user')
    # ### end Alembic commands ###
